Algoritmo "Trabalhando com Tipos Operadores Logicos"

Var
numero1, numero2, soma, subtracao, multiplicacao: inteiro
divisao: real
sucesso: logico
Inicio
Escreval("N1")
leia(numero1)
Escreval("N2")
leia(numero2)
soma<-numero1 + numero2
subtracao <- numero1 - numero2
multiplicacao <- numero1 *numero2
divisao <- numero1 / numero2
//logica verdadeiro ou falso >10
sucesso <-numero1 > 10
Escreval(sucesso)

Fimalgoritmo